import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import BreadcrumbSchema from '@/components/seo/BreadcrumbSchema'

export const metadata: Metadata = {
  title: 'Impression 3D et maquettes d’architecture',
  description: 'Impression 3D de maquettes d’architecture pour soutenances, concours, agences et chefs de projet : volumes, prototypes et accompagnement fichier.',
  alternates: { canonical: 'https://www.inphenix-system.fr/secteurs/architecture' },
}

const audiences = [
  { title: 'Étudiants en architecture', eyebrow: 'Soutenances · rendus · jurys', description: 'Transformez votre modèle numérique en une maquette physique lisible pour votre jury : volumes, implantation, façades et détails importants.', points: ['Aide pour préparer un fichier SketchUp, Rhino, Blender ou STL', 'Choix de l’échelle et du niveau de détail', 'Fabrication en une ou plusieurs parties selon le format'], cta: 'Préparer ma maquette' },
  { title: 'Agences et chefs de projet', eyebrow: 'Concours · clients · conception', description: 'Présentez un projet, validez un détail ou testez un composant avec une maquette et des prototypes conçus pour vos phases projet.', points: ['Maquettes de concours et présentations client', 'Prototypes de façades, assemblages et pièces sur mesure', 'Accompagnement technique de l’échelle à la fabrication'], cta: 'Demander un devis projet' },
]

const steps = [
  ['01', 'Partagez votre projet', 'Envoyez votre fichier, quelques vues ou un brief. Nous identifions l’échelle, le format et les éléments à mettre en valeur.'],
  ['02', 'Validez le rendu', 'Nous échangeons sur la découpe, les matériaux, le niveau de détail et la solution de présentation la plus adaptée.'],
  ['03', 'Recevez votre maquette', 'La fabrication est organisée selon les contraintes de votre projet, avec une maquette prête à présenter ou à tester.'],
]

export default function ArchitecturePage() {
  return <main className="bg-white">
    <BreadcrumbSchema items={[{ name: 'Accueil', path: '/' }, { name: 'Secteurs', path: '/secteurs' }, { name: 'Architecture', path: '/secteurs/architecture' }]} />
    <section className="bg-secondary-900 text-white"><div className="container-custom grid gap-10 py-14 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:py-20"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-300">Architecture · maquettes et prototypes</p><h1 className="mt-5 max-w-3xl text-4xl font-bold leading-tight tracking-[-0.04em] md:text-5xl">Impression 3D pour l’architecture et maquettes architecturales</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-secondary-300">Donnez une présence physique à vos projets architecturaux : maquettes de soutenance, présentations client, concours et prototypes techniques, de votre fichier 3D à une pièce prête à défendre.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#votre-projet" className="rounded-lg bg-primary-500 px-5 py-3 text-sm font-semibold text-white hover:bg-primary-400">Parler de mon projet</Link><Link href="#etapes" className="rounded-lg border border-white/25 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10">Comment ça fonctionne</Link></div></div><div className="relative aspect-[4/3] overflow-hidden rounded-xl border border-white/10 bg-secondary-800 shadow-2xl"><Image src="/images/secteurs/architecture/architecture-1.jpg" alt="Maquette urbaine imprimée en 3D" fill priority sizes="(min-width: 1024px) 500px, 100vw" className="object-cover" /></div></div></section>

    <section id="votre-projet" className="container-custom py-16 lg:py-24"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-600">Un accompagnement adapté</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.035em] text-secondary-900 md:text-4xl">Votre besoin n’est pas le même selon votre projet.</h2><p className="mt-4 text-lg leading-8 text-secondary-600">Choisissez votre point de départ : nous adaptons l’échelle, la préparation du fichier et le niveau de finition à votre objectif.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-2">{audiences.map((audience) => <article key={audience.title} className="rounded-xl border border-secondary-200 p-7 hover:border-primary-200 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary-600">{audience.eyebrow}</p><h3 className="mt-4 text-2xl font-bold tracking-[-0.025em] text-secondary-900">{audience.title}</h3><p className="mt-4 leading-7 text-secondary-600">{audience.description}</p><ul className="mt-6 space-y-3">{audience.points.map((point) => <li key={point} className="flex gap-3 text-sm leading-6 text-secondary-700"><span className="mt-0.5 text-primary-600">✓</span>{point}</li>)}</ul><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary-600 hover:text-primary-700">{audience.cta}<span aria-hidden="true">→</span></Link></article>)}</div></section>

    <section className="bg-secondary-50 py-16 lg:py-24"><div className="container-custom"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-secondary-200"><Image src="/images/secteurs/architecture/architecture-2.jpg" alt="Maquette de bâtiment imprimée en 3D" fill sizes="(min-width: 1024px) 430px, 100vw" className="object-cover" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-600">Ce que nous pouvons réaliser</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.035em] text-secondary-900">Une maquette utile pour expliquer, convaincre ou valider.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-lg border border-secondary-200 bg-white p-5"><h3 className="font-semibold text-secondary-900">Présenter</h3><p className="mt-2 text-sm leading-6 text-secondary-600">Volumes, implantation, façades, bâtiments ou ensembles urbains.</p></div><div className="rounded-lg border border-secondary-200 bg-white p-5"><h3 className="font-semibold text-secondary-900">Tester</h3><p className="mt-2 text-sm leading-6 text-secondary-600">Éléments de façade, assemblages, mobilier et détails techniques.</p></div><div className="rounded-lg border border-secondary-200 bg-white p-5"><h3 className="font-semibold text-secondary-900">Exposer</h3><p className="mt-2 text-sm leading-6 text-secondary-600">Pièce de concours, présentation client, soutenance ou chantier.</p></div><div className="rounded-lg border border-secondary-200 bg-white p-5"><h3 className="font-semibold text-secondary-900">Adapter</h3><p className="mt-2 text-sm leading-6 text-secondary-600">Découpe, assemblage et finition adaptés à l’échelle du projet.</p></div></div></div></div></div></section>

    <section id="etapes" className="container-custom py-16 lg:py-24"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-600">Un processus clair</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.035em] text-secondary-900">De votre fichier à votre maquette.</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{steps.map(([number, title, description]) => <div key={number} className="border-t-2 border-primary-500 pt-5"><p className="font-mono text-sm text-primary-600">{number}</p><h3 className="mt-3 text-xl font-bold text-secondary-900">{title}</h3><p className="mt-3 leading-7 text-secondary-600">{description}</p></div>)}</div></section>

    <section className="border-y border-secondary-200 bg-secondary-50 py-16"><div className="container-custom grid max-w-5xl gap-8 md:grid-cols-[0.8fr_1.2fr] md:items-center"><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-secondary-200"><Image src="/images/secteurs/architecture/architecture-3.jpg" alt="Maquette d’intérieur et plan de logement imprimés en 3D" fill sizes="(min-width: 768px) 400px, 100vw" className="object-cover" /></div><div><h2 className="text-2xl font-bold tracking-[-0.03em] text-secondary-900">Vous n’avez pas encore un fichier prêt à imprimer ?</h2><p className="mt-4 leading-7 text-secondary-600">Vous pouvez partir d’un fichier SketchUp, Rhino, Blender, STL, OBJ ou STEP. Si le modèle doit être nettoyé, simplifié, découpé ou préparé pour l’impression, nous pouvons vous aider à cadrer les étapes nécessaires avant fabrication.</p></div></div></section>

    <section className="bg-primary-600 py-16 text-white"><div className="container-custom flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div><h2 className="text-3xl font-bold tracking-[-0.035em]">Parlons de votre maquette.</h2><p className="mt-3 max-w-2xl text-primary-100">Partagez votre échéance, votre fichier ou simplement votre intention : nous vous aiderons à définir la bonne approche.</p></div><Link href="/contact" className="shrink-0 rounded-lg bg-white px-6 py-3 text-sm font-semibold text-primary-700 hover:bg-primary-50">Nous contacter</Link></div></section>
  </main>
}
